"""empty message

Revision ID: 207f717113f3
Revises: d53142e8fd74
Create Date: 2024-01-02 23:46:56.621506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '207f717113f3'
down_revision = 'd53142e8fd74'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
