"""empty message

Revision ID: 545cf49e6e0d
Revises: 55f27fc4ddf0
Create Date: 2024-01-02 18:46:29.652537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '545cf49e6e0d'
down_revision = '55f27fc4ddf0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
