"""empty message

Revision ID: 55f27fc4ddf0
Revises: 
Create Date: 2024-01-01 23:03:08.826392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f27fc4ddf0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Board',
    sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('writer', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('del_yn', sa.VARCHAR(length=1), nullable=False),
    sa.Column('updater', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('post_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Board')
    # ### end Alembic commands ###
