"""empty message

Revision ID: 863c6ae48972
Revises: 207f717113f3
Create Date: 2024-01-03 19:00:08.157168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863c6ae48972'
down_revision = '207f717113f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
