"""empty message

Revision ID: d53142e8fd74
Revises: 545cf49e6e0d
Create Date: 2024-01-02 19:35:49.011277

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd53142e8fd74'
down_revision = '545cf49e6e0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
